---
  - name: install node and npm
    apt:
      name: "{{ item }}"
    with_items:
    - nodejs
    become: yes

####### Ubuntu can just apt-get npm, Debian has to use curl script to fetch it ########
  - name: install node and npm
    apt:
      name: "{{ item }}"
    with_items:
    - npm
    become: yes
    when: distro == 'bionic'

  - name: use curl script to fetch/install node and npm
    shell: curl -sL https://deb.nodesource.com/setup_6.x | bash -
    become: yes
    when: distro == 'stretch'
    
  - name: npm install dependencies
    npm:
      path: "{{ webgui_dir }}"

  - name: write environment information to production.env
    lineinfile:
      dest: "{{ webgui_dir }}/production.env"
      regexp: "{{ item.field }}"
      line: "{{ item.line }}"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0755
    with_items:
    - {field: 'DB_PASSWORD', line: 'DB_PASSWORD={{ mysql_password }}'}
    - {field: 'DB_USER', line: 'DB_USER={{ username }}'}

  - name: copy production.env file to .env
    copy: 
      src: "{{ webgui_dir }}/production.env"
      dest: "{{ webgui_dir }}/.env"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0755

  - name: write information to webgui.conf
    lineinfile:
      dest: "{{ webgui_dir }}/install_scripts/webgui.conf"
      regexp: "{{ item.field }}"
      line: "{{ item.line }}"
    with_items:
    - {field: "server_name", line: "  server_name network.{{ network_name }};"}

  - name: copy website configuration file
    copy:
      src: "{{ webgui_dir }}/install_scripts/webgui.conf"
      dest: "/etc/nginx/sites-available/webgui"
    become: yes

  - name: symlink website into sites-enabled
    file:
      src: "/etc/nginx/sites-available/webgui"
      dest: "/etc/nginx/sites-enabled/webgui"
      state: link
    become: yes    
    
  - name: add localhost dns pointers in /etc/hosts 
    lineinfile:
      dest: "/etc/hosts"
      regexp: "network"
      line: "127.0.0.1 network.{{ network_name }}"
    become: yes
  
  - name: dynamically write colte_webgui.service
    lineinfile:
      dest: "{{ webgui_dir }}/install_scripts/colte_webgui.service"
      regexp: "{{ item.field }}"
      line: "{{ item.line }}"
      owner: "{{ username }}"
      group: "{{ username }}"
    with_items:
    - {field: "ExecStart", line: "ExecStart=/bin/bash -c \"{{ webgui_dir }}/bin/www >> /var/log/colte/webgui.log 2>&1\""}
    - {field: "User", line: "User={{ username }}"}
    - {field: "Group", line: "Group={{ username }}"}
    - {field: "WorkingDirectory", line: "WorkingDirectory={{ webgui_dir }}"}

  - name: copy webgui.service to /etc/systemd/system
    copy: 
      src: "{{ webgui_dir }}/install_scripts/colte_webgui.service"
      dest: "/etc/systemd/system/colte_webgui.service"
      mode: 0644
    become: yes

  - name: start colte webgui via systemd
    systemd: state=started name=colte_webgui
    become: yes
